export const TOGGLE_NAV = 'TOGGLE_NAV';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const FETCH_BARBERS = 'FETCH_BARBERS';
export const CREATE_BARBER = 'CREATE_BARBER';
export const DELETE_BARBER = 'DELETE_BARBER';
export const UPDATE_BARBER = 'UPDATE_BARBER';
