// UI
export const TOGGLE_NAVIGATION = 'TOGGLE_NAVIGATION';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

// BARBERS
export const FETCH_BARBERS = 'FETCH_BARBERS';
export const CREATE_BARBER = 'CREATE_BARBER';
export const DELETE_BARBER = 'DELETE_BARBER';
export const UPDATE_BARBER = 'UPDATE_BARBER';

// SERVICES
export const FETCH_SERVICES = 'FETCH_SERVICES';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
